### PR TITLE
Added Bot Detector compatible list

### PR DESCRIPTION
**Pull request by WalterWhite3**
This list can be used with Bot Detector to automatically call out and kick other Bot Detector users with their own weapon.
This is useful since it will also work with cheats other than cathook.

When using TF2BD against other players, you'll have to disable "Auto temp mute" and lower the "Auto votekick delay" for the best results.

### CODE REVIEW

**Comment by d3fc0n6** [comment]
I like the idea of it but the only issue I can see with it is updating it automatically with the current IDs. As at the moment I don't have anything to correctly add ids into an appropriate format correctly.

**Comment by WalterWhite3** [comment]
I see. I think that I'll try writing a simple php script that automatically converts the latest cathook list into the Bot Detector format.
This way the bot detector could simply request the latest list from said php script and update it.

**Comment by WalterWhite3** [comment]
Alright, I've just written a small php file that converts all entries into the Bot Detector format.
This should automatically update the list everytime it changes.

**Comment by d3fc0n6** [comment]
Seems alright, though thinking it'd be better to just leave the URL to the list itself in the repo for example
`"update_url"; "https://raw.githubusercontent.com/d3fc0n6/PazerList/master/playerlist.tf2bd.json"`

(mainly this as I will be uploading a new version of the list every time we make a commit so)

**Comment by WalterWhite3** [comment]
Done. I initially thought of ConvertPazerList.php as a simple self-hosted translator that the Bot Detector users would use. This way you wouldn't need to update the Bot Detector list every time. But that's fine too.

**Comment by d3fc0n6** [comment]
No worries, I'll leave the script incase anyone wants to. Other than that this looks good to me. 👍

**Pull request merged**
